// packages/svelte/src/lib/PanelGroup.svelte
<script lang="ts">
  import type { SharedPanelGroupProps } from "@window-splitter/interface";
  import { measureGroupChildren } from "@window-splitter/interface";
  import {
    buildTemplate,
    groupMachine,
    prepareSnapshot,
    prepareItems,
    getPanelGroupPixelSizes,
    getPanelGroupPercentageSizes,
    isPanelData,
  } from "@window-splitter/state";
  import type { GroupMachineContextValue, Unit } from "@window-splitter/state";
  import { setContext } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  export { PanelGroupHandle } from "@window-splitter/interface";

  export interface PanelGroupProps
    extends SharedPanelGroupProps,
      HTMLAttributes<HTMLDivElement> {
    id: string;
  }

  let {
    children,
    orientation = "horizontal",
    autosaveStrategy = "localStorage",
    autosaveId,
    snapshot,
    ...attrs
  }: PanelGroupProps = $props();

  if (
    !snapshot &&
    typeof window !== "undefined" &&
    autosaveId &&
    autosaveStrategy === "localStorage"
  ) {
    const localSnapshot = localStorage.getItem(autosaveId);

    if (localSnapshot) {
      snapshot = JSON.parse(localSnapshot) as GroupMachineContextValue;
    }
  }

  const defaultId = $props.id();
  const id = autosaveId || defaultId;

  const [initialState, send, machineState] = groupMachine(
    {
      orientation,
      groupId: id,
      autosaveStrategy,
      ...(snapshot ? prepareSnapshot(snapshot) : undefined),
    },
    (s) => updateContext(s)
  );

  const context = $state<GroupMachineContextValue>(initialState);
  function updateContext(s: GroupMachineContextValue) {
    for (const key in s) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (context as any)[key] = (s as any)[key];
    }
  }

  setContext("send", send);
  setContext("state", context);
  setContext("id", machineState);

  const isPrerender = $state({ current: true });
  setContext("isPrerender", isPrerender);
  $effect(() => {
    isPrerender.current = false;
  });

  let elementRef = $state<HTMLDivElement>();

  $effect(() => {
    const observer = new ResizeObserver(([entry]) => {
      if (!entry) return;
      if (entry.contentRect.width > 0 && entry.contentRect.height > 0) {
        send({ type: "setSize", size: entry.contentRect });
      }
    });

    if (elementRef) {
      observer.observe(elementRef);
    }

    return () => observer.disconnect();
  });

  let childIds = $derived(context.items.map((i) => i.id).join(","));

  $effect(() => {
    // re-render when the childIds change
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    childIds;

    return measureGroupChildren(id, (childrenSizes) => {
      send({ type: "setActualItemsSize", childrenSizes });
    });
  });

  let template = $derived(buildTemplate(context));

  $effect(() => {
    send({ type: "unlockGroup" });
    return () => send({ type: "lockGroup" });
  });

  export const getId = () => id;
  export const getPixelSizes = () => getPanelGroupPixelSizes(context);
  export const getPercentageSizes = () => getPanelGroupPercentageSizes(context);
  export const getTemplate = () =>
    buildTemplate({ ...context, items: prepareItems(context) });
  export const getState = () =>
    machineState.current === "idle" ? "idle" : "dragging";
  export const setSizes = (updates: Array<Unit>) => {
    for (let index = 0; index < updates.length; index++) {
      const item = context.items[index];
      const update = updates[index];

      if (item && isPanelData(item) && update) {
        send({
          type: "setPanelPixelSize",
          panelId: item.id,
          size: update,
        });
      }
    }
  };
</script>

<div
  {...attrs}
  data-panel-group-wrapper
  bind:this={elementRef}
  style:display="grid"
  style:grid-template-columns={context.orientation === "horizontal"
    ? template
    : undefined}
  style:grid-template-rows={context.orientation === "vertical"
    ? template
    : undefined}
  {id}
>
  {@render children?.()}
</div>

<style>
  :where([data-panel-group-wrapper]) {
    height: 100%;
  }
</style>

// packages/vue/src/PanelGroup.vue
<script setup lang="ts">
import {
  measureGroupChildren,
  PanelGroupHandle,
  SharedPanelGroupProps,
} from "@window-splitter/interface";
import {
  buildTemplate,
  getPanelGroupPercentageSizes,
  getPanelGroupPixelSizes,
  groupMachine,
  GroupMachineContextValue,
  isPanelData,
  prepareSnapshot,
  Unit,
} from "@window-splitter/state";
import {
  useId,
  type HTMLAttributes,
  provide,
  ref,
  computed,
  onMounted,
  watchEffect,
} from "vue";

type PanelGroupProps = SharedPanelGroupProps & /* @vue-ignore */ HTMLAttributes;

const {
  orientation = "horizontal",
  autosaveStrategy = "localStorage",
  snapshot: snapshotProp,
  autosaveId,
  id,
  ...attrs
} = defineProps<PanelGroupProps>();

let snapshot = snapshotProp;

if (
  !snapshot &&
  typeof window !== "undefined" &&
  autosaveId &&
  autosaveStrategy === "localStorage"
) {
  const localSnapshot = localStorage.getItem(autosaveId);

  if (localSnapshot) {
    snapshot = JSON.parse(localSnapshot) as GroupMachineContextValue;
  }
}

const isPrerender = ref(true);
provide("isPrerender", isPrerender);

const groupId = autosaveId || id || useId();
const [initialState, send, machineState] = groupMachine(
  {
    orientation: orientation,
    groupId,
    autosaveStrategy: autosaveStrategy,
    ...(snapshot ? prepareSnapshot(snapshot) : undefined),
  },
  (s) => {
    context.value = { ...s };
  },
);

onMounted(() => {
  isPrerender.value = false;
});

const context = ref(initialState);
const gridStyle = computed(() => {
  const template = buildTemplate(context.value);
  return {
    height: "100%",
    display: "grid",
    gridTemplateColumns: orientation === "horizontal" ? template : undefined,
    gridTemplateRows: orientation === "vertical" ? template : undefined,
  };
});

provide("send", send);
provide("state", context);
provide("id", machineState);

const elementRef = ref<HTMLDivElement | null>(null);

onMounted(() => {
  const observer = new ResizeObserver(([entry]) => {
    if (!entry) return;
    if (entry.contentRect.width > 0 && entry.contentRect.height > 0) {
      send?.({ type: "setSize", size: entry.contentRect });
    }
  });

  if (elementRef.value) {
    observer.observe(elementRef.value);
  }

  return () => observer.disconnect();
});

const childIds = computed(() =>
  context.value?.items.map((i) => i.id).join(","),
);

watchEffect(() => {
  // re-render when the childIds change
  // eslint-disable-next-line @typescript-eslint/no-unused-expressions
  childIds.value;

  return measureGroupChildren(groupId, (childrenSizes) =>
    send({ type: "setActualItemsSize", childrenSizes }),
  );
});

onMounted(() => {
  send({ type: "unlockGroup" });
  return () => send({ type: "lockGroup" });
});

defineExpose<PanelGroupHandle>({
  getId: () => groupId,
  getPixelSizes: () => getPanelGroupPixelSizes(context.value),
  getPercentageSizes: () => getPanelGroupPercentageSizes(context.value),
  getTemplate: () => buildTemplate(context.value),
  getState: () => (machineState.current === "idle" ? "idle" : "dragging"),
  setSizes: (updates) => {
    for (let index = 0; index < updates.length; index++) {
      const item = context.value?.items[index];
      const update = updates[index];

      if (item && isPanelData(item) && update) {
        send({
          type: "setPanelPixelSize",
          panelId: item.id,
          size: update,
        });
      }
    }
  },
});
</script>

<template>
  <div
    v-bind="attrs"
    ref="elementRef"
    data-panel-group-wrapper
    :id="groupId"
    :style="gridStyle"
  >
    <slot></slot>
  </div>
</template>
