// packages/vue/src/Panel.vue
<script setup lang="ts">
import {
  getPanelDomAttributes,
  PanelHandle,
  SharedPanelProps,
} from "@window-splitter/interface";
import {
  getPanelPercentageSize,
  getPanelPixelSize,
  GroupMachineContextValue,
  haveConstraintsChangedForPanel,
  initializePanel,
  isPanelData,
  PanelData,
  SendFn,
} from "@window-splitter/state";
import {
  computed,
  HTMLAttributes,
  inject,
  onMounted,
  onUnmounted,
  Ref,
  useId,
  watchEffect,
} from "vue";

type PanelProps = SharedPanelProps<boolean> & HTMLAttributes;
const {
  min,
  max,
  id,
  collapsible,
  collapsedSize,
  onCollapseChange,
  collapseAnimation,
  onResize,
  defaultCollapsed,
  default: defaultSize,
  isStaticAtRest,
  collapsed,
  ...attrs
} = defineProps<PanelProps>();

const panelId = id || useId();
const send = inject<SendFn>("send");
const state = inject<Ref<GroupMachineContextValue>>("state");
const isPrerender = inject<Ref<boolean>>("isPrerender");

const initPanel = (): PanelData => {
  return initializePanel({
    id: panelId,
    min,
    max,
    collapsible,
    collapsed: collapsed,
    collapsedSize,
    onCollapseChange: onCollapseChange
      ? { current: onCollapseChange }
      : undefined,
    collapseAnimation,
    onResize: onResize ? { current: onResize } : undefined,
    defaultCollapsed,
    default: defaultSize,
    isStaticAtRest,
  });
};

const panelData = computed(() => {
  const item = state?.value?.items.find((i) => i.id === panelId);
  if (!item || !isPanelData(item)) return undefined;
  return item;
});

let dynamicPanelIsMounting = false;

if (panelData.value) {
  send?.({
    type: "rebindPanelCallbacks",
    data: {
      id: panelId,
      onCollapseChange: onCollapseChange
        ? { current: onCollapseChange }
        : undefined,
      onResize: onResize ? { current: onResize } : undefined,
    },
  });
} else {
  if (isPrerender?.value) {
    send?.({ type: "registerPanel", data: initPanel() });
  } else {
    dynamicPanelIsMounting = true;
  }
}

onMounted(() => {
  const groupId = state?.value?.groupId;
  if (!groupId || !dynamicPanelIsMounting) return;

  const groupElement = document.getElementById(groupId);
  if (!groupElement) return;

  const panelElement = document.getElementById(panelId);
  if (!panelElement) return;

  const order = Array.from(groupElement.children).indexOf(panelElement);
  if (typeof order !== "number") return;

  send?.({
    type: "registerDynamicPanel",
    data: { ...initPanel(), order },
  });
  dynamicPanelIsMounting = false;
});

const contraintChanged = computed(
  () =>
    !dynamicPanelIsMounting &&
    haveConstraintsChangedForPanel(initPanel(), panelData.value),
);

watchEffect(() => {
  if (!contraintChanged.value) return;
  send?.({ type: "updateConstraints", data: initPanel() });
});

onUnmounted(() => {
  requestAnimationFrame(() => send?.({ type: "unregisterPanel", id: panelId }));
});

defineExpose<PanelHandle>({
  getId: () => panelId,
  collapse: () => {
    if (!panelData.value?.collapsible) return;
    send?.({ type: "collapsePanel", panelId: panelId, controlled: true });
  },
  isCollapsed: () =>
    Boolean(panelData.value?.collapsible && panelData.value?.collapsed),
  expand: () => {
    if (!panelData.value?.collapsible) return;
    send?.({ type: "expandPanel", panelId: panelId, controlled: true });
  },
  isExpanded: () =>
    Boolean(panelData.value?.collapsible && !panelData.value?.collapsed),
  getPixelSize: () => getPanelPixelSize(state!.value, panelId),
  getPercentageSize: () => getPanelPercentageSize(state!.value, panelId),
  setSize: (size) =>
    send?.({ type: "setPanelPixelSize", panelId: panelId, size }),
});

const isControlledCollapse = computed(
  () => panelData.value?.collapseIsControlled,
);

watchEffect(() => {
  if (!isControlledCollapse.value) return;

  if (collapsed) {
    send?.({ type: "collapsePanel", panelId: panelId, controlled: true });
  } else {
    send?.({ type: "expandPanel", panelId: panelId, controlled: true });
  }
});

const computedProps = computed(() => {
  const currentPanel = panelData.value;

  return {
    ...attrs,
    ...getPanelDomAttributes({
      groupId: state?.value?.groupId,
      id: panelId,
      collapsible: currentPanel?.collapsible,
      collapsed: currentPanel?.collapsed,
    }),
    style: {
      minWidth: 0,
      minHeight: 0,
      overflow: "hidden",
    },
  };
});
</script>

<template>
  <div v-bind="computedProps">
    <slot />
  </div>
</template>

// packages/svelte/src/lib/Panel.svelte
<script lang="ts">
  import type { SharedPanelProps } from "@window-splitter/interface";
  import { getContext } from "svelte";
  import {
    initializePanel,
    isPanelData,
    haveConstraintsChangedForPanel,
    getPanelPercentageSize,
    getPanelPixelSize,
  } from "@window-splitter/state";
  import type {
    PanelData,
    GroupMachineContextValue,
    SendFn,
    Unit,
  } from "@window-splitter/state";
  import { getPanelDomAttributes } from "@window-splitter/interface";
  import type { HTMLAttributes } from "svelte/elements";

  export { PanelHandle } from "@window-splitter/interface";

  export interface PanelProps
    extends SharedPanelProps<boolean>,
      HTMLAttributes<HTMLDivElement> {}

  let {
    children,
    min,
    max,
    id: _id,
    collapsible,
    collapsed,
    collapsedSize,
    onCollapseChange,
    collapseAnimation,
    onResize,
    defaultCollapsed,
    default: defaultSize,
    isStaticAtRest,
    ...attrs
  }: PanelProps = $props();

  const defaultId = $props.id();
  const id = _id || defaultId;
  const send = getContext<SendFn>("send");
  const state = getContext<GroupMachineContextValue>("state");

  const initPanel = (): PanelData =>
    initializePanel({
      id,
      min,
      max,
      collapsible,
      collapsed,
      collapsedSize,
      onCollapseChange: { current: onCollapseChange },
      collapseAnimation,
      onResize: { current: onResize },
      defaultCollapsed,
      default: defaultSize,
      isStaticAtRest,
    });

  const isPrerender = getContext<{ current: boolean }>("isPrerender");
  const panelData = () => {
    const item = state?.items.find((i) => i.id === id);
    if (!item || !isPanelData(item)) return undefined;
    return item;
  };

  let dynamicPanelIsMounting = false;

  if (panelData()) {
    send({
      type: "rebindPanelCallbacks",
      data: {
        id,
        onCollapseChange: { current: onCollapseChange },
        onResize: { current: onResize },
      },
    });
  } else {
    if (isPrerender.current) {
      send({ type: "registerPanel", data: initPanel() });
    } else {
      dynamicPanelIsMounting = true;
    }
  }

  const contraintChanged = $derived(
    !dynamicPanelIsMounting &&
      haveConstraintsChangedForPanel(initPanel(), panelData())
  );

  $effect(() => {
    if (!contraintChanged) return;
    send({ type: "updateConstraints", data: initPanel() });
  });

  const dynamicPanelData = initPanel();

  $effect(() => {
    if (!dynamicPanelIsMounting) return;

    const groupElement = document.getElementById(state.groupId);
    if (!groupElement) return;

    const panelElement = document.getElementById(id);
    if (!panelElement) return;

    const order = Array.from(groupElement.children).indexOf(panelElement);
    if (typeof order !== "number") return;

    send({
      type: "registerDynamicPanel",
      data: { ...dynamicPanelData, order },
    });
    dynamicPanelIsMounting = false;
  });

  $effect(() => () => {
    requestAnimationFrame(() => send({ type: "unregisterPanel", id }));
  });

  const isControlledCollapse = $derived(panelData()?.collapseIsControlled);

  $effect(() => {
    if (!isControlledCollapse) return;

    if (collapsed) {
      send?.({ type: "collapsePanel", panelId: id, controlled: true });
    } else {
      send?.({ type: "expandPanel", panelId: id, controlled: true });
    }
  });

  const domAttributes = () => {
    const currentPanel = panelData();

    return getPanelDomAttributes({
      groupId: state.groupId,
      id,
      collapsible: currentPanel?.collapsible,
      collapsed: currentPanel?.collapsed,
    });
  };

  export const getId = () => id;
  export const collapse = () => {
    if (!panelData()?.collapsible) return;
    send({ type: "collapsePanel", panelId: id, controlled: true });
  };
  export const isCollapsed = () =>
    Boolean(panelData()?.collapsible && panelData()?.collapsed);
  export const expand = () => {
    if (!panelData()?.collapsible) return;
    send({ type: "expandPanel", panelId: id, controlled: true });
  };
  export const isExpanded = () =>
    Boolean(panelData()?.collapsible && !panelData()?.collapsed);
  export const getPixelSize = () => getPanelPixelSize(state, id);
  export const setSize = (size: Unit) => {
    send({ type: "setPanelPixelSize", panelId: id, size });
  };
  export const getPercentageSize = () => getPanelPercentageSize(state, id);
</script>

<div
  {...attrs}
  {...domAttributes()}
  style:min-width={0}
  style:min-height={0}
  style:overflow="hidden"
>
  {@render children?.()}
</div>
